name: balancemate
description: "The only (probably) and best (maybe) way to calculate your counterweight position with unmatched mathmatical precision."


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets: 
    - assets/Amazing and extremely cool telescope icon that's certainly not just dev art ;D.png
    - assets/telescopes.json
    - assets/mounts.json
    - assets/counterweights.json
    - assets/counterweight_setups.json

